version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 5
    labels: ["dependencies", "security"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]
