[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = False
warn_unused_ignores = False
warn_return_any = False
no_strict_optional = True
allow_redefinition = True
pretty = True
show_error_codes = True
exclude = (?x)(^views/|^build/|^dist/|^_attic/|^\.venv/|^__pycache__/)

[mypy-PySide6.*]
ignore_missing_imports = True
